### ISSUE TITLE
incomplete warning message

### ISSUE THREAD

**Issue by jfass** [pdxgx/neoepiscope#11]
After installing with pip3 and testing with the current repo, I tried swapping the columns (ours is tumor then normal) of a Varscan output file, and received the following:

```
$ neoepiscope swap -i varscan_filtered.vcf -o varscan_filtered.swapped.vcf
/home/ubuntu/.local/lib/python3.5/site-packages/neoepiscope/file_processing.py:94: Warning: Reading NORMAL as normal tissue and TUMOR as tumor tissue
  Warning,
```

... and that's it. Now, it actually swapped the sample columns ... but then why the warning?

**Comment by maryawood** [comment]
The warning occurs regardless of the ordering of your VCF, simply to alert you to which columns are being treated as the normal and tumor samples, respectively. That being said, we can probably elaborate on the warning, so we will make it more verbose for a future release.

Do you mean that your VCF is _now_ (after swapping) in the order of tumor then normal? That is the desired outcome of running `neoepiscope swap`, and what it looks like happened based on the warning you shared. If it was originally in that order, there's no need to swap columns!
