### ISSUE TITLE
"-g" in prep? exists in README.md, but not usage message

### ISSUE THREAD

**Issue by jfass** [pdxgx/neoepiscope#13]
Hi - I installed a couple of weeks ago using pip, so I think I'm up to date version-wise. But I'm hoping to add germline variation to the predicted neoepitopes, so I used a command from the GitHub README.md, to this effect:

#########cut#########
Predict haplotype phasing

Next, run HapCUT2 with your merged or somatic VCF (make sure to use --indels 1 when running extractHAIRS if you wish to predict neoepitopes resulting from insertions and deletions). Before calling neoepitopes, prep your HapCUT2 output to included unphased mutations as their own haplotypes and flag germline variants if relevant:

neoepiscope prep -v <VCF> -c <HAPCUT2 OUTPUT> [-g <GERMLINE VCF>] -o <ADJUSTED HAPCUT OUTPUT>

Options:

-v, --vcf path to VCF file used to generate HapCUT2 output

-g, --germline-vcf	path to germline VCF used in neoepiscope merge

-c, --hapcut2-output path to original HapCUT2 output

-o, --output path to output file

-p, --phased	flag input VCF as phased with GATK ReadBackedPhasing
##########cut#########

... so I'm specifying a germline-only VCF file, using "-g". However, I get this:
```
neoepiscope: error: unrecognized arguments: -g SS.normal.vcf
```
... and 'neoepiscope prep -h' doesn't show a "-g" option like the readme does. What should I do here?

Thanks in advance!

**Comment by maryawood** [comment]
Thank you for pointing out this issue! This is a relic in the documentation from a previous version of neoepiscope. You will just need to use the `-v` option with your merged VCF file, the `-c` option with your HapCUT2 output, and `-o` option with the path where you'd liked the adjusted haplotype output to be written. 

We will update the README to reflect this!

**Comment by jfass** [comment]
Cool! -- TY
